# Generated by Django 3.0.5 on 2022-11-22 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_auto_20221122_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesaltapaciente',
            name='fechaAdmision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.Paciente'),
        ),
    ]
